version: "3.7"

services:
    acme.sh:
        build:
            context: ./build
            dockerfile: Dockerfile-acme
        ports:
            - "80:80/tcp"
        volumes:
            - ./cert:/cert
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        env_file: .env
        environment:
            - "RELOADCMD=docker restart ${NGINX_CONTAINER}"

    ss-server:
        image: acrisliu/shadowsocks-libev
        command:
            - "/start-server.sh"
        volumes:
            - ./scripts/start-server.sh:/start-server.sh:ro
        restart: on-failure
        env_file: .env

    nginx:
        container_name: ${NGINX_CONTAINER}
        image: nginx:1.23.1
        volumes:
          - ./nginx/templates:/etc/nginx/templates:ro
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
          - ./cert:/etc/nginx/cert:ro
          - ./scripts/wait-for-cert.sh:/wait-for-cert.sh
        restart: on-failure
        ports:
          - "443:443/tcp"
        env_file: .env
        ulimits:
          nofile:
            soft: 65535
            hard: 65535
        entrypoint: ["/wait-for-cert.sh", "/docker-entrypoint.sh", "nginx"]
